version: '3.8'
version: '3.8'

services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: uuuu
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  web:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: uuuu
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    ports:
      - "3111:3111"
    depends_on:
      - db
    networks:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
